@startuml RF 1.11/1.12
skinparam actorStyle awesome
!theme spacelab
rectangle "RF 027/028"
:Coordenador: as coordenador #text:blue
:Sistema: as sistema #text:blue

(Ratificar requisição) as ratificar_requisicao
(Assinar digitalmente a requisição) as assinar_requisicao
(Encaminhar requisição para a escolaridade) as encaminhar_requisicao
(Alterar status da requisição) as alterar_status_requisicao


coordenador --> assinar_requisicao
sistema --> alterar_status_requisicao
assinar_requisicao ..> ratificar_requisicao #text:blue : <<include>>
ratificar_requisicao ..> encaminhar_requisicao #text:blue : <<include>>  
encaminhar_requisicao ..> alterar_status_requisicao #text:blue : <<include>>  
@enduml