@startuml RF 1.8/1.10
skinparam actorStyle awesome
!theme spacelab
rectangle "RF 024/026"
:Coordenador: as coordenador #text:blue
:Sistema: as sistema #text:blue
(Enviar requisições para a comissão) as enviar_requisicoes_comissao
(Enviar email para a comissão) as enviar_email_comissao
(Rejeitar avaliação de requisição) as rejeitar_avaliacao_requisicao
(Solicitar reavaliação da requisição) as solicitar_reavaliacao_requisicao

coordenador --> enviar_requisicoes_comissao
coordenador --> rejeitar_avaliacao_requisicao
sistema -right-->(enviar_email_comissao)
rejeitar_avaliacao_requisicao ..> solicitar_reavaliacao_requisicao #text:blue : <<include>>  
enviar_requisicoes_comissao ..> enviar_email_comissao #text:blue : <<include>>  
rejeitar_avaliacao_requisicao ..> enviar_email_comissao #text:blue : <<include>>  

@enduml