@startuml atividades

    start
    if (Acesso à internet?) then (sim)
        :Efetuar Login;
        :Navegar para o dasbhboard do discente;
        :Ir para o cadastro de uma nova requisição no dasbhboard;
        if (Existe um Rascunho?) then (não)
            :Adicionar uma nova requisição;
            :Informar dados da requisição;
        else (sim)
            :Selecionar rascunho já existente;
            :Adicionar informações e arquivos dos certificados;
        endif
        if (As informações são válidas?) then (sim)
            if (Deseja efetuar o cadastro?) then (sim)
                :Redirecionar para o dasbhboard com a requisição cadastrada;
                :Dashboard com as informações da requisição cadastrada;
            else (não)
                if(Deseja salvar o rascunho?) then (sim)
                    :Salvar rascunho;
                    :Dashboard com as informações salvas em um rascunho;
                else (não)
                    end 
                endif
            endif    
            stop
        else (não)
            end
        endif
    else (não)
        end
    endif

@enduml