@startuml Diagrama c2 - container
skinparam actorStyle awesome

node "Sistema ACs"{
    [Aplicação web\nTs + React + NextJs] as front
    [API\nJava + Spring boot] as back
    database "PostgreSQL"

    front -left--> back: usa
    back -left--> PostgreSQL: CRUD
}

node "Cliente SMTP" as SMTP{
}

node "Via Cep WS" as ViaCep{
}

Actor Usuário #Blue;line.dashed;text:blue
Actor Escolaridade #f0d890;line.dashed;text:blue

back -down-> SMTP #line:gray;text:blue : usa
back -down--> ViaCep #line:gray;text:blue : usa
Usuário -up-> front #line:gray;text:blue : Acessa
SMTP -down-> Usuário #line:gray;text:blue : Envia e-mail
SMTP -down-> Escolaridade #line:gray;text:blue : Envia e-mail
@enduml