@startuml Requisição

[*] -> EmRascunho : Requisicao Criada
EmRascunho --> EmAnaliseCoordenacao : Requisicao submetida
EmAnaliseCoordenacao -> EmAnaliseComissao : Enviado\npara comissao
EmAnaliseComissao --> EmAnaliseCoordenacao : Analisado\npela comissao
EmAnaliseCoordenacao -> EncaminhadoParaEscolaridade : Analisado pela Coordenacao
EncaminhadoParaEscolaridade --> EmRecurso : Pedido de\ncontagem
EmRecurso --> EmAnaliseCoordenacao : Revisao aprovada
EmRecurso --> Concluido : Revisao negada
EncaminhadoParaEscolaridade --> Concluido : Finalizado
Concluido --> [*]

@enduml