@startuml RF_027
!theme spacelab
skinparam actorStyle awesome
:Perfil Discente: as PD
rectangle requisito_funcional as "RF 027"

(Dashboard do Discente) as RF17
(Visualizar Solicitações) as RF14
(Arquivar Solicitação) as RF27
(Solicitação Arquivada) as SoliArqui

PD --> RF17
RF17 --> RF14
RF14 --> RF27
RF27 --> SoliArqui

note right of RF14
  Deve existir um botão de arquivar
  para permitir o arquivamento
  de solicitações desejadas pelo discente.
end note

note left of SoliArqui
    Após arquivada, vai ser possível
    visulizar as solicitações arquivadas
    em outro modal.
end note

@enduml
