@startuml Diagrama c1 - contexto
skinparam actorStyle awesome

rectangle "Perfis de usuários" as usuarios{
    actor Aluno #text:blue
    actor Comissão #text:blue
    actor Coordenador #text:blue
    actor Administrador #text:blue
}

rectangle sistema_acs as "Sistema ACs" #f0d890

rectangle "Elementos externos" as external_elements {
    agent cliente_smtp as "Cliente SMTP"
    agent via_cep as "Via cep API"
}

Administrador -down-> Coordenador
Coordenador -down-> Comissão
Comissão -down-> Aluno
usuarios -down-> sistema_acs

sistema_acs -down-> external_elements
@enduml