INSERT INTO public.courses(id, additional_hours, name, acronym)
VALUES
    (1, 180, 'Ciências Biológicas', 'BIO'),
    (2, 180, 'Ciências Sociais', 'CS'),
    (3, 180, 'Computação', 'LC'),
    (4, 180, 'Educação Física', 'EF'),
    (5, 180, 'Geografia', 'GEO'),
    (6, 180, 'História', 'HIS'),
    (7, 180, 'Letras com habilitação em língua portuguesa e espanhola', 'LLE'),
    (8, 180, 'Letras com habilitação em língua portuguesa e inglesa', 'LLI'),
    (9, 180, 'Letras com habilitação em língua portuguesa e suas literaturas', 'LLL'),
    (10, 180, 'Matemática', 'MAT'),
    (11, 180, 'Pedagogia', 'PED'),
    (12, 180, 'Administração', 'ADM'),
    (13, 180, 'Ciências Biológicas', 'BBIO'),
    (14, 225, 'Direito', 'DIR'),
    (15, 180, 'Educação Física', 'BEF'),
    (16, 180, 'Enfermagem', 'ENF'),
    (17, 225, 'Engenharia Civil', 'ECIV'),
    (18, 225, 'Engenharia da Computação', 'ECOM'),
    (19, 225, 'Engenharia de Controle e Automação', 'ECA'),
    (20, 180, 'Engenharia de Software', 'ES'),
    (21, 225, 'Engenharia Elétrica de Telecomunicações', 'TEL'),
    (22, 225, 'Engenharia Elétrica Eletrônica', 'ETN'),
    (23, 225, 'Engenharia Elétrica Eletrotécnica', 'ETT'),
    (24, 225, 'Engenharia Mecânica', 'EMEC'),
    (25, 180, 'Física de Materiais', 'FM'),
    (26, 225, 'Fisioterapia', 'FISIO'),
    (27, 225, 'Medicina', 'MED'),
    (28, 225, 'Nutrição', 'NUT'),
    (29, 225, 'Odontologia', 'ODONT'),
    (30, 180, 'Psicologia', 'PSI'),
    (31, 180, 'Saúde Coletiva', 'SC'),
    (32, 180, 'Serviço Social', 'SS'),
    (33, 180, 'Sistemas de Informação', 'SI'),
    (34, 180, 'Terapia Ocupacional', 'TO'),
    (35, 90, 'Tecnologia em Logística', 'TL');