@startuml Certificado

[*] -> Anexado : Associado a\nrequisicao
Anexado --> AguardandoAnalise : Submissão\nda requisicao\ncom certificados
AguardandoAnalise -> CertificadoEmAnalise : Encaminhamento para\nCoordenação
CertificadoEmAnalise -> Recusado : Certificado recusado 
CertificadoEmAnalise -> Aceito : Certificado aceito
CertificadoEmAnalise -> ContagemDeHorasEmAnalise : Encaminhamento da Requisição\n com Certificado
ContagemDeHorasEmAnalise --> CertificadoEmAnalise : Contagem finalizada

@enduml