@startuml Diagrama C3 - Componentes
node "Front-End" as front {

}

node "API" as api  {
    rectangle "Serviço" as servico {

    }

    rectangle "Controlador" as controlador{
    }

    rectangle "Repositório" as repositorio{
    }

    rectangle "Domínio" as dominio {
        [Modelo] as modelo
        [DTO] as dto
        [Resposta] as resposta
    }

    front -right--> api

    controlador -> servico #line:gray;text:blue : usa
    servico -> repositorio #line:gray;text:blue : usa

    controlador --> resposta #line:gray;line.dashed;text:blue : manipula
    servico --> dto #line:gray;line.dashed;text:blue : manipula
    repositorio --> modelo #line:gray;line.dashed;text:blue : ORM
}

database "Banco de dados" as bd {
}
repositorio -> bd
@enduml